### ISSUE TITLE
Github Topics

### ISSUE THREAD

**Issue by tylercd100** [laravel-validation-rules/ip#1]
Looks like one of your topics is "iPhone" instead of "IP"
![image](https://user-images.githubusercontent.com/4522226/30552491-6029deb6-9c5b-11e7-803e-70ca85a7fe01.png)

**Comment by clarkeash** [comment]
Thanks, I don't even remember setting these 😄

**Comment by tylercd100** [comment]
Yeah it was probably Scott :P

**Comment by ssx** [comment]
Definitely guilty, or just some great SEO work ;)
