### ISSUE TITLE
Not able to install on Laravel 7 

### ISSUE THREAD

**Issue by anilkoeri** [laravel-validation-rules/ip#3]
getting below error

Problem 1
    - Installation request for laravel-validation-rules/ip ^1.3 -> satisfiable by laravel-validation-rules/ip[1.3.0].
    - Conclusion: remove symfony/http-foundation v5.0.7
    - Conclusion: don't install symfony/http-foundation v5.0.7
    - laravel-validation-rules/ip 1.3.0 requires symfony/http-foundation ^3.3 -> satisfiable by symfony/http-foundation[3.3.x-dev, 3.4.x-dev].
    - Can only install one of: symfony/http-foundation[3.3.x-dev, v5.0.7].
    - Can only install one of: symfony/http-foundation[3.4.x-dev, v5.0.7].
    - Installation request for symfony/http-foundation (locked at v5.0.7, required as ^5.0) -> satisfiable by symfony/http-foundation[v5.0.7].

**Comment by anilkoeri** [comment]
sorry my bad

**Comment by ssx** [comment]
@anilkoeri are you still having this issue? does it fail to install on Laravel 8?
